title: ALAMOSE
description: Authentic Learning-based Modules for DevOps Security Education
theme: jekyll-theme-cayman

url: "https://paser4se.github.io/"

# #remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme